name: build and check the Chocolatey package
on:
  push:
    tags:
    - "*"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - run: choco feature enable -n allowGlobalConfirmation
    - run: choco pack
    - run: choco install therion --debug --verbose --source .
    - run: choco apikey --key ${{ secrets.CHOCOLATEY_API_KEY }} --source https://push.chocolatey.org
    - run: choco push --source https://push.chocolatey.org
